version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: tcs
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      DATABASE_HOST: db
  web:
    build: ./web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tcs
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3257:3257"
    depends_on:
      - db
    restart: on-failure 
